spring:
  application:
    name: engineering-thesis
  profiles:
    active: local
  datasource:
    url:
    username:
    password:
    tomcat:
      testOnBorrow: true
      validationQuery: SELECT 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB