spring:
  application:
    name: engineering-thesis
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://mysql.agh.edu.pl:3306/malina
    username: malina
    password: 8gPGN7HkUnsBDKdU
    tomcat:
      testOnBorrow: true
      validationQuery: SELECT 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB